ganachecli:
  domain: ganachecli.example.com
  path: thef
  image:
    repository: trufflesuite/ganache-cli
    tag: latest
  webSocketSecret: my-secret-for-connecting-to-ethstats
  service:
    type: ClusterIP