apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ganachecli.fullname" . }}
  labels:
    app: {{ template "ganachecli.name" . }}
    chart: {{ template "ganachecli.chart" . }}
    release: {{ .Release.Name }}
    component: ganachecli
    heritage: {{ .Release.Service }}
  {{- if .Values.ganachecli.ingress }}
  {{- range $key, $value := .Values.ganachecli.ingress.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  annotations:
    traefik.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ganachecli.whitelistIP }}
  {{- if .Values.ganachecli.ingress }}
  {{- range $key, $value := .Values.ganachecli.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
    traefik.ingress.kubernetes.io/auth-type: "basic"
    traefik.ingress.kubernetes.io/auth-secret: {{ .Values.ganachecli.secret }}
spec:
  rules:
  - host: {{ .Values.ganachecli.domain }}
    http:
      paths:
      - path: /{{ .Values.ganachecli.path }}
        backend:
          serviceName: {{ template "ganachecli.fullname" . }}
          servicePort: {{ .Release.Name }}